.codeclimate.yml
.gitignore
.travis.yml
requirements.txt
src/qinfer/__init__.py

Hello.
I'm coming back with a much lighter PR than #29. This also contains work in response to issue #28 
* I set up [Travis](https://travis-ci.org/) on my GitHub repo, and provided a config file with a workaround for numpy and scipy installation
* Since I'm using PyCharm, i added my IDE files to .gitignore
* I fixed an import in ```qinfer.__init__```, where ```_exceptions``` instead of ```qinfer._exceptions``` was being imported. The test library showed that this was throwing an ```ImportError```, and the new import matches the syntax of the others in ```qinfer```. Based on my builds, this didn't break any code.
- [pytest](http://pytest.org/latest/), an alternative to Python's [unittest](https://docs.python.org/2/library/unittest.html) library, offers a tighter default regex to recognize …

Travis, Coveralls, CodeClimate, and a broken import

---

src/qinfer/smc.py

Tensordot is much better optimized for BLAS libraries such as MKL or OpenBlas. I get approximately a 10x speed-up compared to the einsum call in bayes_update function call. See [this post](http://stackoverflow.com/questions/23650449/numpy-np-einsum-array-multiplication-using-multiple-cores)  for my motivation. It may be useful to see what other speedups can be obtained by replacing einsum.

Qinfer optimizations

---

src/qinfer/ipy.py

If ``ipywidgets`` is not installed, the new ``IPythonProgressBar`` class would raise an error due to ``ipw`` being set to ``None``. This PR fixes this behavior to provide a more useful error message, informing the user that ``ipywidgets`` is required for IPython interaction.

ImportError raised if ipywidgets is missing during IPythonProgressBar.

---

.travis.yml

This PR adds Python 3.5 to the build matrix by removing install arguments for packages that are not available on the ``conda python=3.5`` repos.

Removed extraneous conda install args, added Py35 to travis build mtx.

---

README.rst
doc/source/intro.rst

This PR changes the install instructions dramatically to recommend Anaconda for Python 3.5. This should be simpler, but currently the Travis build is broken for 3.5 such that we can't actually claim that it's tested. I'll submit another PR to turn on 3.5 testing, then this PR should make more sense.

Changed install to point to pip/Anaconda.

---

doc/source/conf.py
doc/source/guide/distributions.rst
doc/source/guide/models.rst
doc/source/guide/multicos.py
doc/source/guide/parallel.rst
doc/source/guide/smc.rst
src/qinfer/rb.py

Make a list of small fixes/improvements:
* define |+> state in model docs
* explain what `pr0_to_likelihood` does
* add simulation example code to the `MultiCosModel` for many `expparams` and an explanation of the `dtype` used.
* mention that is_valid is used by resamplers
* add ipyparallel docs links

Fix cleanup

---

.travis.yml
setup.cfg
setup.py

The travis deploy suggested by @scasagrande almost worked, but I made a minor mistake in setting it up. Specifically, I forgot to [add ``cd ~/`` to the ``before_deploy`` stage](http://stackoverflow.com/questions/36635650/travisci-deploy-cannot-find-setup-py). I don't want to push a new tag for ``v1.0b4``, so I'll deploy manually for now and it should be in place for the next version.

Fix for travis → PyPI deploy.

---

README.rst

This should help address issue #37 by adding some more instructions for Anaconda Python, "regular"-Python, as well as pointing to using the PyPI package for QInfer instead of having to use Git.

More detail for qinfer installation instructions

---

src/qinfer/abstract_model.py
src/qinfer/utils.py

This PR makes handling of scalar and 0-dimensional arrays more robust in ``Model.likelihood``. In particular, ``call_count`` and ``pr0_to_likelihood_array`` should both now accept scalars and 0-dim arrays without errors.

Fix shape robustness

---

requirements.txt

Not sure what ``requirements.txt`` is used for, but unit testing is failing for me because of the ``dtype ``option in ``np.linspace``.

Insert required numpy version.

---

src/qinfer/perf_testing.py

This PR generalizes ``perf_test_multiple`` to include two additional important cases: when the true model and estimation model admit different numbers of parameters, and when the true model has a timestep update that must be considered. In the first case, both the estimated and true modelparameter vectors are now correctly recorded, while the loss is restricted to those parameters shared between the two (aligning at the right, in keeping with NumPy convention). In the second, a call to ``true_model.update_timestep`` is now made after each ``simulate_experiment`` call in the updater loop.

Generalization for mismatched model shape and timestep updates in perf_test

---

.gitignore
doc/source/guide/tomography.rst

This PR disables the annoying doctest in ``tomography.rst`` that has been breaking CI builds for a while. Once we figure out ``repr(type)`` in a portable way, I recommend re-enabling this test.

Disable typerepr doctest

---

src/qinfer/tomography/bases.py
src/qinfer/tomography/distributions.py
src/qinfer/tomography/expdesign.py
src/qinfer/tomography/legacy.py
src/qinfer/tomography/plotting_tools.py

This PR introduces @ihincks's commit ccb776dc8a3a1cec0d7f1140de08506a7dfe3c44 into master. As suggested in #71, ``qinfer.tomography`` should check if QuTiP is at least version 3.2, not 3.1 as is currently done, since many of the random sampling features were not present in 3.1.

Changed required qutip version to >= 3.2

---

.travis.yml
src/qinfer/tests/test_concrete_models.py

This PR should address Python 3.x failures in CI tests by installing everything into a new Conda env. Currently, the root conda env is being changed in-place to the desired Python version, which has caused a whole host of failures.

Change Travis CI builds to use new Conda env instead of root environment.

---

src/qinfer/ale.py
src/qinfer/derived_models.py
src/qinfer/utils.py

As per #22, this PR changes ``ALEApproximateModel`` to inherit from ``DerivedModel``, completing the transition over to using ``DerivedModel`` as a base class for all models which decorate other models with additional functionality.

Changed ALEApproximateModel to inherit from DerivedModel.

---

src/qinfer/smc.py
src/qinfer/tests/base_test.py
src/qinfer/tests/test_abstract_model.py
src/qinfer/tests/test_smc.py
src/qinfer/tests/test_test.py

This PR adds a new property, ``SMCUpdater.min_n_ess``, to track the smallest effective sample size observed in the process of updating a distribution. Please see #88 for discussions.

New SMCUpdater.min_n_ess property

---

src/qinfer/smc.py
src/qinfer/tomography/plotting_tools.py

The recent improvements to region estimation plotting with rebits (#84 and #86) turn out to have a bug when used from ``qinfer.tomography.plotting_tools``. This PR fixes the bug.

Bugfix for rebit regionest plotting w/ fancy indexing.

---

doc/source/apiref/distributions.rst
src/qinfer/distributions.py
src/qinfer/metrics.py
src/qinfer/tests/test_distributions.py
src/qinfer/tests/test_region_estimates.py

This PR simply adds the new distribution `ParticleDistribution` and corresponding tests. All methods and properties of `SMCUpdater` which were (in my opinion) relevant to a bare particle distribution were copied over (but left intact). This is the first step of #105. The next step, in my view, is to implement the hierarchy `ParticleDistribution`>`AbstractUpdater`>`SMCUpdater`.
It would be worthwhile for someone to compare the properties and methods of `ParticleDistribution` and `SMCUpdater` to check if my choices are appropriate and comprehensive.
[Sorry for all the whitespace changes my text editor did automatically]

New distribution: ParticleDistribution

---

src/qinfer/tests/test_smc.py

Python 2.7 and 3.5 require numpy slice bounds to have integer type, but `np.ceil` outputs a float; this PR adds an explicit cast.

Fixed bug in test_smc.py

---

setup.cfg
src/qinfer/domains.py
src/qinfer/tests/base_test.py
src/qinfer/tests/test_domains.py

This PR adds a fairly comprehensive set of tests for concrete classes inheriting from `Domain`. This caught one bug in `MultinomialDomain.example_point` due to a comma (fixed), and a couple of pretty obscure bugs, like reporting `1j` is in `RealDomain` since technically `1j<np.inf` (also fixed).
Note: Sorry, again, for all the trailing whitespace removal. My stupid (but nice in most other ways) text editor does this by default and without warning whenever you save a file. I have now figured out how to disable it.

Tests for Domains

---

src/qinfer/resamplers.py
src/qinfer/smc.py

This PR adds a parameter to the Lui-West resampler called `default_n_particles` which optionally stores a default number of particles to draw. Furthermore, `SMCUpdater` has the default behaviour of setting `default_n_particles` of the `resampler` to the `__init__` input `n_particles`.
To the best of my knowledge, this should have no side-effects at present because (currently) the resampler is the only thing that changes the number of particles in the whole qinfer library.
The idea here is to allow `canonicalize` and `update_timestep` to drop particles (ala rejection filtering) without affecting the long-term stability. For example, if `update_timestep` takes particles outside of the allowed region, one of the most sensible things to do is drop them; trying to reflect them back in or …

Feature: Lui-West default number of particles

---

.travis.yml

With the release of QuTiP 4.1 and its use of C++ features, we need to add ``g++`` as a build dependency on Travis to make sure we can compile the qutip package correctly. This should fix build errors seen in #125  and #126. Starting the PR to trigger builds and test whether it works.

Update travis config for QuTiP 4.1.

---

doc/source/guide/citing.rst
doc/source/guide/index.rst
doc/source/intro.rst
src/qinfer/__init__.py
src/qinfer/_due.py
src/qinfer/ale.py
src/qinfer/rb.py
src/qinfer/resamplers.py
src/qinfer/tomography/distributions.py
src/qinfer/utils.py

This WIP PR addresses #128 by adding citation metadata to ``__init__.py``. This citation is guarded with the tag ``["implementation"]``, with the idea that citations to underlying theory could be added to individual functions with the ``["theory"]`` tag.

WIP: Citation metadata w/ duecredit

---

doc/source/guide/citing.rst

Just added a note about the new `due.dump()` function.

Update duecredit doc

---

doc/source/apiref/domains.rst
src/qinfer/domains.py
src/qinfer/tests/test_domains.py
src/qinfer/utils.py

This PR adds a new domain called `ProductDomain` which takes the cartesian product of any number of factor domains. This is done using numpy structured dtypes, so you can, for example, take the product of `MultinomialDomain` and `RealDomain` and end up with a dtype like `[('k', int, 3), ('f1', float)]`.
This PR should be merged after #116 and #115.

Feature: ProductDomain

---

.travis.yml
doc/source/apiref/test_models.rst
doc/source/guide/models.rst
setup.py
src/qinfer/tests/__init__.py
src/qinfer/tests/base_test.py
src/qinfer/tests/test_test.py

The function `test_model` has apparently been broken for a while; it depended on some old names, etc. This fixes it and makes it visible as `qinfer.tests.test_model`, thereby addressing #131 too.

Fix test_model

---

src/qinfer/clustering.py
src/qinfer/distributions.py
src/qinfer/resamplers.py
src/qinfer/smc.py
src/qinfer/utils.py

This is a first suggestion how to move all the particle mean/covariance related logic into the `ParticleDistribution` class itself. This allows the user to provide his/her own moment-computing functions as show in [this Notebook](https://github.com/dseuss/qinfer-examples/blob/master/circular_statistics.ipynb).
I have not touched the clustering-resampler related stuff so far since this is work in progress. Once we have agreed on the right interface, this can certainly be done.
The other place that should be fixed is how the LW resampler combines the two resampling strategies [here](https://github.com/QInfer/python-qinfer/blob/master/src/qinfer/resamplers.py#L326). For each particle, this is a mean over two (virtual) particles with weights `a` and `1-a`. In the Notebook I get around the …

Feature custom meanfn
